---
language: ruby
bundler_args: "--without system"
script: "bundle exec rspec --color --format documentation spec/unit"
notifications:
  email: false
sudo: false
jdk:
  - openjdk11
before_install: gem install bundler -v '< 2' --no-document
matrix:
  include:
    - stage: r10k tests
      rvm: 2.7.0
    - stage: r10k tests
      rvm: 2.6.5
    - stage: r10k tests
      rvm: 2.5.0
    - stage: r10k tests
      rvm: 2.4.0
    - stage: r10k tests
      rvm: 2.3.0
    - stage: r10k tests
      rvm: jruby
    - stage: r10k container tests
      dist: focal
      language: ruby
      services:
        - docker
      rvm: 2.6.6
      env:
        - DOCKER_COMPOSE_VERSION=1.25.5
        # necessary to prevent overwhelming TravisCI build output limits
        - DOCKER_BUILD_FLAGS="--progress plain"
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl --location https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname --kernel-name`-`uname --machine` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - set -e
        - cd docker
        - make lint
        - make build
        - make test
